const express = require('express')
const app = express()
const mongoose = require('mongoose')
const dotenv = require('dotenv')
const authRoute = require("./routes/signInandUp.js")
const profileRoute = require("./routes/profile.js")
const SubGredditRoute = require("./routes/MySubGreddit.js")
const verifysignin = require("./routes/verifysignin.js")
const allsubgreddits = require("./routes/allsubgreddits.js")
const postroute = require("./routes/posts.js")
const savedpostsroute = require("./routes/savedposts.js")
const reportroute = require("./routes/Reports.js")
const cors = require('cors')
dotenv.config()
console.log(process.env.DB_ACCESS)
mongoose.connect(process.env.DB_ACCESS,()=>console.log("DB connected"))
app.use(express.json())
app.use(cors())
app.use("/api/signin",authRoute)
app.use("/api/profile",profileRoute)
app.use("/api/mysubgreddits",SubGredditRoute)
app.use("/api/verifysignin",verifysignin)
app.use("/api/regposts",postroute)
app.use("/api/reports",reportroute)
app.use("/api/allsubgreddits",allsubgreddits)
app.use("/api/savedposts",savedpostsroute)
app.listen(5000,() => console.log("server is up and running"))